exclude:
- /Tribler/Core/APIImplementation/.*
- /Tribler/Core/CacheDB/.*
- /Tribler/Core/Category/.*
- /Tribler/Core/Config/.*
- /Tribler/Core/CreditMining/.*
- /Tribler/Core/DecentralizedTracking/.*
- /Tribler/Core/DownloadConfig.py
- /Tribler/Core/DownloadState.py
- /Tribler/Core/Libtorrent/.*
- /Tribler/Core/Modules/__init__.py
- /Tribler/Core/Modules/channel/.*
- /Tribler/Core/Modules/process_checker.py
- /Tribler/Core/Modules/restapi/__init__.py
- /Tribler/Core/Modules/restapi/channels/.*
- /Tribler/Core/Modules/restapi/create_torrent_endpoint.py
- /Tribler/Core/Modules/restapi/debug_endpoint.py
- /Tribler/Core/Modules/restapi/downloads_endpoint.py
- /Tribler/Core/Modules/restapi/events_endpoint.py
- /Tribler/Core/Modules/restapi/rest_manager.py
- /Tribler/Core/Modules/restapi/root_endpoint.py
- /Tribler/Core/Modules/restapi/search_endpoint.py
- /Tribler/Core/Modules/restapi/settings_endpoint.py
- /Tribler/Core/Modules/restapi/shutdown_endpoint.py
- /Tribler/Core/Modules/restapi/state_endpoint.py
- /Tribler/Core/Modules/restapi/statistics_endpoint.py
- /Tribler/Core/Modules/restapi/torrentinfo_endpoint.py
- /Tribler/Core/Modules/restapi/torrents_endpoint.py
- /Tribler/Core/Modules/restapi/util.py
- /Tribler/Core/Modules/search_manager.py
- /Tribler/Core/Modules/tracker_manager.py
- /Tribler/Core/Modules/versioncheck_manager.py
- /Tribler/Core/Modules/watch_folder.py
- /Tribler/Core/RemoteTorrentHandler.py
- /Tribler/Core/Session.py
- /Tribler/Core/TFTP/.*
- /Tribler/Core/TorrentChecker/.*
- /Tribler/Core/TorrentDef.py
- /Tribler/Core/Upgrade/.*
- /Tribler/Core/Utilities/.*
- /Tribler/Core/Video/.*
- /Tribler/Core/__init__.py
- /Tribler/Core/defaults.py
- /Tribler/Core/exceptions.py
- /Tribler/Core/leveldbstore.py
- /Tribler/Core/osutils.py
- /Tribler/Core/permid.py
- /Tribler/Core/plyveladapter.py
- /Tribler/Core/simpledefs.py
- /Tribler/Core/statistics.py
- /Tribler/Core/version.py
- /Tribler/Main/.*
- /Tribler/Test/API/.*
- /Tribler/Test/Community/AbstractTestCommunity.py
- /Tribler/Test/Community/Allchannel/.*
- /Tribler/Test/Community/Search/.*
- /Tribler/Test/Community/Triblerchain/__init__.py
- /Tribler/Test/Community/Triblerchain/test_block.py
- /Tribler/Test/Community/Triblerchain/test_startup.py
- /Tribler/Test/Community/Triblerchain/test_triblerchain_utilities.py
- /Tribler/Test/Community/Trustchain/.*
- /Tribler/Test/Community/Tunnel/.*
- /Tribler/Test/Community/__init__.py
- /Tribler/Test/Community/channel/.*
- /Tribler/Test/Core/Category/.*
- /Tribler/Test/Core/Config/.*
- /Tribler/Test/Core/CreditMining/.*
- /Tribler/Test/Core/Libtorrent/.*
- /Tribler/Test/Core/Modules/Channel/.*
- /Tribler/Test/Core/Modules/RestApi/Channels/.*
- /Tribler/Test/Core/Modules/RestApi/__init__.py
- /Tribler/Test/Core/Modules/RestApi/base_api_test.py
- /Tribler/Test/Core/Modules/RestApi/test_create_torrent_endpoint.py
- /Tribler/Test/Core/Modules/RestApi/test_debug_endpoint.py
- /Tribler/Test/Core/Modules/RestApi/test_downloads_endpoint.py
- /Tribler/Test/Core/Modules/RestApi/test_events_endpoint.py
- /Tribler/Test/Core/Modules/RestApi/test_rest_manager.py
- /Tribler/Test/Core/Modules/RestApi/test_search_endpoint.py
- /Tribler/Test/Core/Modules/RestApi/test_settings_endpoint.py
- /Tribler/Test/Core/Modules/RestApi/test_shutdown_endpoint.py
- /Tribler/Test/Core/Modules/RestApi/test_state_endpoint.py
- /Tribler/Test/Core/Modules/RestApi/test_statistics_endpoint.py
- /Tribler/Test/Core/Modules/RestApi/test_torrentinfo_endpoint.py
- /Tribler/Test/Core/Modules/RestApi/test_torrents_endpoint.py
- /Tribler/Test/Core/Modules/RestApi/test_trustchain_endpoint.py
- /Tribler/Test/Core/Modules/RestApi/test_trustchain_statistics_endpoint.py
- /Tribler/Test/Core/Modules/RestApi/test_util.py
- /Tribler/Test/Core/Modules/__init__.py
- /Tribler/Test/Core/Modules/channel/test_channel_manager.py
- /Tribler/Test/Core/Modules/test_process_checker.py
- /Tribler/Test/Core/Modules/test_tracker_manager.py
- /Tribler/Test/Core/Modules/test_versioncheck.py
- /Tribler/Test/Core/Modules/test_watch_folder.py
- /Tribler/Test/Core/TFTP/.*
- /Tribler/Test/Core/TorrentChecker/.*
- /Tribler/Test/Core/Upgrade/.*
- /Tribler/Test/Core/Utilities/.*
- /Tribler/Test/Core/Video/.*
- /Tribler/Test/Core/__init__.py
- /Tribler/Test/Core/base_test.py
- /Tribler/Test/Core/base_test_channel.py
- /Tribler/Test/Core/test_api_misc_utils.py
- /Tribler/Test/Core/test_configparser.py
- /Tribler/Test/Core/test_downloadconfig.py
- /Tribler/Test/Core/test_downloadstate.py
- /Tribler/Test/Core/test_encoding.py
- /Tribler/Test/Core/test_exceptions.py
- /Tribler/Test/Core/test_install_dir.py
- /Tribler/Test/Core/test_instrumentation.py
- /Tribler/Test/Core/test_launch_many_cores.py
- /Tribler/Test/Core/test_leveldb_store.py
- /Tribler/Test/Core/test_leveldb_store_plyvel.py
- /Tribler/Test/Core/test_network_utils.py
- /Tribler/Test/Core/test_notifier.py
- /Tribler/Test/Core/test_osutils.py
- /Tribler/Test/Core/test_permid.py
- /Tribler/Test/Core/test_search_utils.py
- /Tribler/Test/Core/test_session.py
- /Tribler/Test/Core/test_sqlitecachedb.py
- /Tribler/Test/Core/test_sqlitecachedbhandler.py
- /Tribler/Test/Core/test_sqlitecachedbhandler_channels.py
- /Tribler/Test/Core/test_sqlitecachedbhandler_peers.py
- /Tribler/Test/Core/test_sqlitecachedbhandler_preferences.py
- /Tribler/Test/Core/test_sqlitecachedbhandler_torrents.py
- /Tribler/Test/Core/test_sqlitecachedbhandler_votecasts.py
- /Tribler/Test/Core/test_torrent_def.py
- /Tribler/Test/Core/test_torrent_utils.py
- /Tribler/Test/Core/test_unicode.py
- /Tribler/Test/Core/test_utilities.py
- /Tribler/Test/Core/test_win32regchecker.py
- /Tribler/Test/GUI/.*
- /Tribler/Test/__init__.py
- /Tribler/Test/btconn.py
- /Tribler/Test/common.py
- /Tribler/Test/test.sh
- /Tribler/Test/test_as_server.py
- /Tribler/Test/test_magnetlink.py
- /Tribler/Test/test_remote_torrent_handler.py
- /Tribler/Test/test_torrent.py
- /Tribler/Test/twisted_thread.py
- /Tribler/Test/util/.*
- /Tribler/__init__.py
- /Tribler/community/__init__.py
- /Tribler/community/allchannel/.*
- /Tribler/community/channel/.*
- /Tribler/community/search/.*
- /Tribler/community/triblerchain/__init__.py
- /Tribler/community/triblerchain/block.py
- /Tribler/community/trustchain/.*
- /Tribler/community/tunnel/.*
- /TriblerGUI/__init__.py
- /TriblerGUI/core_manager.py
- /TriblerGUI/debug_window.py
- /TriblerGUI/defs.py
- /TriblerGUI/dialogs/.*
- /TriblerGUI/event_request_manager.py
- /TriblerGUI/scripts/.*
- /TriblerGUI/single_application.py
- /TriblerGUI/tribler_action_menu.py
- /TriblerGUI/tribler_app.py
- /TriblerGUI/tribler_request_manager.py
- /TriblerGUI/tribler_window.py
- /TriblerGUI/utilities.py
- /TriblerGUI/vlc.py
- /TriblerGUI/widgets/__init__.py
- /TriblerGUI/widgets/channel_list_item.py
- /TriblerGUI/widgets/channel_torrent_list_item.py
- /TriblerGUI/widgets/channelpage.py
- /TriblerGUI/widgets/circlebutton.py
- /TriblerGUI/widgets/createtorrentpage.py
- /TriblerGUI/widgets/discoveredpage.py
- /TriblerGUI/widgets/discoveringpage.py
- /TriblerGUI/widgets/downloadfilewidgetitem.py
- /TriblerGUI/widgets/downloadprogressbar.py
- /TriblerGUI/widgets/downloadsdetailstabwidget.py
- /TriblerGUI/widgets/downloadspage.py
- /TriblerGUI/widgets/downloadwidgetitem.py
- /TriblerGUI/widgets/editchannelpage.py
- /TriblerGUI/widgets/ellipsebutton.py
- /TriblerGUI/widgets/home_recommended_item.py
- /TriblerGUI/widgets/homepage.py
- /TriblerGUI/widgets/lazyloadlist.py
- /TriblerGUI/widgets/leftmenuplaylist.py
- /TriblerGUI/widgets/loading_list_item.py
- /TriblerGUI/widgets/loadingpage.py
- /TriblerGUI/widgets/manageplaylistpage.py
- /TriblerGUI/widgets/playlist_list_item.py
- /TriblerGUI/widgets/playlistpage.py
- /TriblerGUI/widgets/searchresultspage.py
- /TriblerGUI/widgets/settingspage.py
- /TriblerGUI/widgets/subscribedchannelspage.py
- /TriblerGUI/widgets/subscriptionswidget.py
- /TriblerGUI/widgets/tabbuttonpanel.py
- /TriblerGUI/widgets/text_list_item.py
- /TriblerGUI/widgets/thumbnailwidget.py
- /TriblerGUI/widgets/trustpagegraph.py
- /TriblerGUI/widgets/underlinetabbutton.py
- /TriblerGUI/widgets/videoplayerinfobutton.py
- /TriblerGUI/widgets/videoplayerinfopopup.py
- /TriblerGUI/widgets/videoplayerpage.py
- /TriblerGUI/widgets/videoplayerpositionslider.py
- /TriblerGUI/widgets/videoplayervolumecontainer.py
- /TriblerGUI/widgets/videoplayerwidget.py
- /doc/conf.py
- /mac/makedistmac_64bit.sh
- /twisted/plugins/.*
- /win/locate-python.py
component_depth: 1
languages:
- javascript
- python
- script

